openapi: 3.0.4
info:
  title: Swagger CarritoCompras - OpenAPI 3.0
  description: |-
    API para hacer Pedidos
  contact:
    email: ivangusa@unisabana.edu.co
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/
tags:
  
  - name: store
    description: Administracion de pedidos
 
paths:
  /store/order:
    post:
      tags:
        - store
      summary: Realice su pedido.
      description: Realice un nuevo pedido en la tienda.
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/xml:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
 
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        productName:
          type: string
          example: Manzanas
        totalAmtt:
          type: integer
          format: int32
          example: 10000
        paymentMethod:
          type: string
          example: PSE
        quantity:
          type: integer
          format: int32
          example: 7
        shipDate:
          type: string
          format: date-time
        complete:
          type: boolean
      xml:
        name: order
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            "write:pets": modify pets in your account
            "read:pets": read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header