openapi: 3.0.4
info:
  title: Swagger Validacion Pago - OpenAPI 3.0
  description: |-
    API para hacer Pedidos
  contact:
    email: paolarigo@unisabana.edu.co
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  
  - name: payment
    description: Manager de pagos
 
paths:
  /validate-payment:
    post:
      tags:
        - payment
      summary: Validacion del pago.
      description: Realice la autorizacion del pago.
      operationId: placePayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
          application/xml:
            schema:
              $ref: '#/components/schemas/Payment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
 
components:
  schemas:
    Payment:
      type: object
      properties:
        document:
          type: integer
          format: int64
          example: 10
        amount:
          type: integer
          format: int32
          example: 10000
      xml:
        name: payment
    ApiResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      xml:
        name: '##default'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            "write:pets": modify pets in your account
            "read:pets": read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header